<template>
  <div class="legal-page-root">
    <Header />

    <div class="legal-page-frame">
      <div class="ld-page">
        <aside class="ld-sidebar">
          <div class="ld-sidebar-label">On this page</div>
          <nav @click="onTocNavClick">
            <a
              v-for="item in tocItems"
              :key="item.href"
              :href="item.href"
              :class="{ 'is-active': activeTocHash === item.href }"
            >{{ item.label }}</a>
          </nav>
        </aside>

        <main class="ld-content">
          <div class="ld-doc-header">
            <div class="ld-doc-tag">Legal Document</div>
            <h1 class="ld-doc-title">Terms of Service<br />&amp; EULA</h1>
            <p class="ld-doc-meta">
              <strong>Effective Date:</strong> May 12, 2026 &nbsp;|&nbsp;
              <strong>Last Updated:</strong> May 12, 2026 &nbsp;|&nbsp;
              <strong>Version:</strong> 1.0
            </p>
          </div>

          <div class="ld-callout ld-callout--warn">
            <p>
              <strong>PLEASE READ CAREFULLY.</strong> These Terms of Service ("Terms") constitute a legally binding
              agreement between you and VaptFix.ai. By accessing or using our platform, you acknowledge that you have
              read, understood, and agree to be bound by these Terms. If you do not agree, do not use our services.
            </p>
          </div>

          <section id="acceptance">
            <div class="ld-section-number">01 / ACCEPTANCE</div>
            <h2>Acceptance of Terms</h2>
            <p>
              These Terms govern your access to and use of the VaptFix.ai platform, including all related websites,
              APIs, software, tools, reports, documentation, and services (collectively, the "Service"). By creating an
              account, clicking "I Agree," or otherwise accessing the Service, you agree to these Terms on behalf of
              yourself and, if applicable, the organization you represent.
            </p>
            <p>
              If you are entering into these Terms on behalf of a company or other legal entity, you represent that you
              have the authority to bind that entity to these Terms. If you lack such authority, do not use the Service.
            </p>
          </section>

          <section id="definitions">
            <div class="ld-section-number">02 / DEFINITIONS</div>
            <h2>Definitions</h2>
            <ul>
              <li><strong>"VaptFix.ai," "we," "us," "our"</strong> — the company operating the Service at vaptfix.ai</li>
              <li><strong>"User," "you," "your"</strong> — any individual or entity accessing the Service</li>
              <li><strong>"Customer"</strong> — a User who has entered into a paid subscription or enterprise agreement</li>
              <li><strong>"Service"</strong> — the VaptFix.ai VAPT platform, tools, APIs, and related offerings</li>
              <li><strong>"Scan Target"</strong> — any system, network, URL, IP address, or asset submitted for scanning</li>
              <li>
                <strong>"Authorized Target"</strong> — a Scan Target for which you have obtained explicit written
                authorization from the owner
              </li>
              <li><strong>"Output"</strong> — reports, vulnerability data, findings, and other results generated by the Service</li>
              <li><strong>"Subscription"</strong> — a paid plan granting access to the Service for a defined period</li>
            </ul>
          </section>

          <section id="eligibility">
            <div class="ld-section-number">03 / ELIGIBILITY</div>
            <h2>Eligibility</h2>
            <p>
              You must be at least 18 years old and capable of entering into a legally binding agreement to use the
              Service. The Service is intended for use by security professionals, IT teams, and organizations conducting
              legitimate security assessments. Use of the Service for any unlawful purpose is strictly prohibited.
            </p>
          </section>

          <section id="license">
            <div class="ld-section-number">04 / LICENSE GRANT</div>
            <h2>License Grant</h2>
            <p>
              Subject to your compliance with these Terms and timely payment of applicable fees, VaptFix.ai grants you a
              <strong>limited, non-exclusive, non-transferable, non-sublicensable, revocable license</strong> to:
            </p>
            <ul>
              <li>Access and use the Service for your internal security assessment purposes</li>
              <li>Generate, view, and download Output for your authorized systems</li>
              <li>Integrate with the VaptFix.ai API in accordance with API documentation and rate limits</li>
            </ul>
            <p>
              This license does not include the right to resell, redistribute, reverse engineer, decompile, or create
              derivative works based on the Service.
            </p>
          </section>

          <section id="permitted-use">
            <div class="ld-section-number">05 / PERMITTED USE</div>
            <h2>Permitted Use</h2>
            <p>
              You may use the Service only to scan and assess systems for which you are the owner or have obtained
              <strong>explicit, documented written authorization</strong> from the system owner. This includes:
            </p>
            <ul>
              <li>Your own infrastructure, networks, and web applications</li>
              <li>Customer or client systems under a formal penetration testing agreement</li>
              <li>Third-party systems where you hold documented authorization in scope</li>
            </ul>
            <div class="ld-callout">
              <p>
                <strong>Bug Bounty Programs:</strong> Use of the Service against systems covered by a bug bounty program
                is permitted only when the program's rules expressly allow the use of automated scanning tools and within
                the defined scope.
              </p>
            </div>
          </section>

          <section id="prohibited">
            <div class="ld-section-number">06 / PROHIBITED CONDUCT</div>
            <h2>Prohibited Conduct</h2>
            <p>You must NOT use the Service to:</p>
            <ul>
              <li>Scan, probe, or attack systems you do not own or lack written authorization to test</li>
              <li>Conduct denial-of-service (DoS) or distributed denial-of-service (DDoS) attacks</li>
              <li>Exploit discovered vulnerabilities for unauthorized access or data exfiltration</li>
              <li>Circumvent, disable, or interfere with security features of the Service</li>
              <li>Attempt to access other users' accounts, data, or scan results</li>
              <li>Use the Service to develop or distribute offensive cyberweapons or malware</li>
              <li>Violate any applicable law, regulation, or third-party rights</li>
              <li>Resell, broker, or sublicense access to the Service to unauthorized third parties</li>
              <li>Scrape, harvest, or extract data from the Service beyond your authorized Output</li>
              <li>Misrepresent your identity or organizational affiliation</li>
            </ul>
            <div class="ld-callout ld-callout--warn">
              <p>
                <strong>Unauthorized scanning is illegal.</strong> Scanning systems without proper authorization may
                constitute a criminal offense under the Computer Fraud and Abuse Act (CFAA), the UK Computer Misuse Act,
                the EU Directive on Attacks Against Information Systems, and equivalent legislation globally. VaptFix.ai
                will cooperate fully with law enforcement investigations.
              </p>
            </div>
          </section>

          <section id="accounts">
            <div class="ld-section-number">07 / ACCOUNTS</div>
            <h2>Accounts &amp; Security</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activities
              that occur under your account. You must:
            </p>
            <ul>
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Enable multi-factor authentication (MFA) where available</li>
              <li>
                Immediately notify us of any unauthorized use at
                <a href="mailto:security@vaptfix.ai">security@vaptfix.ai</a>
              </li>
              <li>Not share account credentials with unauthorized individuals</li>
            </ul>
            <p>
              VaptFix.ai will not be liable for losses resulting from unauthorized account access caused by your failure
              to maintain credential security.
            </p>
          </section>

          <section id="subscriptions">
            <div class="ld-section-number">08 / SUBSCRIPTIONS &amp; PAYMENT</div>
            <h2>Subscriptions &amp; Payment</h2>

            <h3>Billing</h3>
            <p>
              Subscriptions are billed in advance on a monthly or annual basis. All fees are stated in USD unless
              otherwise agreed. You authorize us to charge your designated payment method on each billing date.
            </p>

            <h3>Renewals</h3>
            <p>
              Subscriptions renew automatically at the end of each billing period unless you cancel at least 24 hours
              before renewal via your account settings or by contacting
              <a href="mailto:billing@vaptfix.ai">billing@vaptfix.ai</a>.
            </p>

            <h3>Price Changes</h3>
            <p>
              We may modify pricing with 30 days' prior written notice. Continued use after the effective date constitutes
              acceptance of the new pricing.
            </p>

            <h3>Refunds</h3>
            <p>
              Annual subscription fees are refundable within 14 days of initial purchase if the Service fails to function
              materially as described. Monthly subscriptions are non-refundable. Enterprise agreements are governed by
              separate commercial terms.
            </p>

            <h3>Taxes</h3>
            <p>
              You are responsible for all applicable taxes, levies, and duties. Where required by law, VaptFix.ai will
              collect and remit taxes on your behalf.
            </p>
          </section>

          <section id="ip">
            <div class="ld-section-number">09 / INTELLECTUAL PROPERTY</div>
            <h2>Intellectual Property</h2>

            <h3>Our IP</h3>
            <p>
              The Service, including all software, algorithms, user interfaces, trademarks, logos, documentation, and
              underlying technology, is owned by VaptFix.ai and protected by intellectual property laws. Nothing in these
              Terms transfers any IP ownership to you.
            </p>

            <h3>Your Data &amp; Output</h3>
            <p>
              You retain full ownership of your Scan Targets, Input data, and the Output generated for your systems. You
              grant VaptFix.ai a limited license to process your data solely to provide the Service. We do not use your
              vulnerability data or scan results to train models or for any purpose beyond service delivery.
            </p>

            <h3>Feedback</h3>
            <p>
              If you provide feedback or suggestions, you grant us a perpetual, irrevocable, royalty-free license to use
              such feedback to improve the Service without any obligation to you.
            </p>
          </section>

          <section id="confidentiality">
            <div class="ld-section-number">10 / CONFIDENTIALITY</div>
            <h2>Confidentiality</h2>
            <p>
              Each party agrees to hold the other's Confidential Information (including vulnerability findings, scan
              data, and pricing) in strict confidence using at least the same degree of care it uses for its own
              confidential information, but no less than reasonable care. Confidentiality obligations survive termination
              of these Terms for 3 years.
            </p>
            <p>
              VaptFix.ai will not disclose your scan results or vulnerability data to any third party except as required by
              law or with your explicit consent.
            </p>
          </section>

          <section id="disclaimers">
            <div class="ld-section-number">11 / DISCLAIMERS</div>
            <h2>Disclaimers</h2>
            <div class="ld-callout ld-callout--warn">
              <p>
                <strong>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE."</strong> TO THE MAXIMUM EXTENT PERMITTED BY
                LAW, VAPTFIX.AI EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF
                MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
              </p>
              <p>
                WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE, OR THAT ALL
                VULNERABILITIES IN YOUR SYSTEMS WILL BE DETECTED. SECURITY ASSESSMENTS ARE POINT-IN-TIME AND DO NOT
                GUARANTEE THE ABSENCE OF VULNERABILITIES.
              </p>
            </div>
          </section>

          <section id="liability">
            <div class="ld-section-number">12 / LIMITATION OF LIABILITY</div>
            <h2>Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</p>
            <ul>
              <li>VAPTFIX.AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES</li>
              <li>
                OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE GREATER OF: (A)
                THE AMOUNT YOU PAID IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B) USD $100
              </li>
            </ul>
            <p>These limitations apply regardless of the theory of liability, even if we have been advised of the possibility of such damages.</p>
          </section>

          <section id="indemnification">
            <div class="ld-section-number">13 / INDEMNIFICATION</div>
            <h2>Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless VaptFix.ai, its officers, directors, employees, and agents
              from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees)
              arising out of or related to:
            </p>
            <ul>
              <li>Your use of the Service in violation of these Terms</li>
              <li>Scanning or testing systems without proper authorization</li>
              <li>Your violation of any applicable law or third-party rights</li>
              <li>Your negligence or willful misconduct</li>
            </ul>
          </section>

          <section id="termination">
            <div class="ld-section-number">14 / TERMINATION</div>
            <h2>Termination</h2>
            <p>Either party may terminate these Terms upon written notice. VaptFix.ai may suspend or terminate your access immediately and without notice if:</p>
            <ul>
              <li>You materially breach these Terms</li>
              <li>We have reason to believe you are using the Service for unauthorized scanning</li>
              <li>Required to do so by law or court order</li>
              <li>Continued operation creates a security risk to other users</li>
            </ul>
            <p>
              Upon termination, you must cease all use of the Service. Sections on IP, Confidentiality, Disclaimers,
              Liability, Indemnification, and Governing Law survive termination.
            </p>
          </section>

          <section id="governing-law">
            <div class="ld-section-number">15 / GOVERNING LAW</div>
            <h2>Governing Law &amp; Disputes</h2>
            <p>
              These Terms are governed by the laws of [Jurisdiction — e.g., the State of Delaware, USA], without regard to
              conflict of law principles. Any disputes shall be resolved by binding arbitration administered by the
              American Arbitration Association (AAA) under its Commercial Arbitration Rules, with proceedings conducted in
              English.
            </p>
            <p>
              Notwithstanding the foregoing, either party may seek injunctive relief in any court of competent jurisdiction
              to prevent irreparable harm. The UN Convention on Contracts for the International Sale of Goods does not
              apply to these Terms.
            </p>
          </section>

          <section id="contact">
            <div class="ld-section-number">16 / CONTACT</div>
            <h2>Contact</h2>
            <div class="ld-callout">
              <p>
                <strong>VaptFix.ai — Legal Team</strong><br />
                Email: <a href="mailto:legal@vaptfix.ai">legal@vaptfix.ai</a><br />
                Billing: <a href="mailto:billing@vaptfix.ai">billing@vaptfix.ai</a><br />
                General: <a href="mailto:hello@vaptfix.ai">hello@vaptfix.ai</a>
              </p>
            </div>
          </section>

          <LegalDocInnerFooter />
        </main>
      </div>
    </div>
  </div>
</template>

<script>
import Header from '@/components/admin-component/Header.vue';
import LegalDocInnerFooter from '@/components/admin-component/LegalDocInnerFooter.vue';

export default {
  name: 'TermsOfServiceView',
  components: {
    Header,
    LegalDocInnerFooter,
  },
  data() {
    return {
      activeTocHash: '',
      tocItems: [
        { href: '#acceptance', label: 'Acceptance' },
        { href: '#definitions', label: 'Definitions' },
        { href: '#eligibility', label: 'Eligibility' },
        { href: '#license', label: 'License Grant' },
        { href: '#permitted-use', label: 'Permitted Use' },
        { href: '#prohibited', label: 'Prohibited Conduct' },
        { href: '#accounts', label: 'Accounts' },
        { href: '#subscriptions', label: 'Subscriptions & Payment' },
        { href: '#ip', label: 'Intellectual Property' },
        { href: '#confidentiality', label: 'Confidentiality' },
        { href: '#disclaimers', label: 'Disclaimers' },
        { href: '#liability', label: 'Limitation of Liability' },
        { href: '#indemnification', label: 'Indemnification' },
        { href: '#termination', label: 'Termination' },
        { href: '#governing-law', label: 'Governing Law' },
        { href: '#contact', label: 'Contact' },
      ],
    };
  },
  watch: {
    '$route.hash'() {
      this.$nextTick(() => this.syncTocFromRoute());
    },
  },
  mounted() {
    document.documentElement.classList.add('legal-doc-sticky-context');
    this.$nextTick(() => this.syncTocFromRoute());
  },
  beforeUnmount() {
    document.documentElement.classList.remove('legal-doc-sticky-context');
  },
  methods: {
    syncTocFromRoute() {
      const hashes = this.tocItems.map((i) => i.href);
      const h = this.$route.hash;
      if (h && hashes.includes(h)) this.activeTocHash = h;
      else this.activeTocHash = hashes[0] || '';
    },
    onTocNavClick(e) {
      const a = e.target.closest?.('a[href^="#"]');
      if (!a || !e.currentTarget.contains(a)) return;
      const href = a.getAttribute('href');
      if (href) this.activeTocHash = href;
    },
  },
};
</script>

<style scoped>
/* Mirrors PrivacyPolicyView — home palette #241447 / #0f696e */
.legal-page-root {
  min-height: 100vh;
  padding-top: 72px;
  padding-bottom: 24px;
  padding-left: clamp(10px, 3vw, 24px);
  padding-right: clamp(10px, 3vw, 24px);
  background: #e8ecf1;
  box-sizing: border-box;
}

.legal-page-frame {
  width: 100%;
  max-width: 1080px;
  margin-left: auto;
  margin-right: auto;
  padding-left: clamp(20px, 4vw, 40px);
  padding-right: clamp(20px, 4vw, 40px);
  padding-bottom: 2rem;
  box-sizing: border-box;
  background-color: #ffffff;
  background-image: radial-gradient(#ebe6f3 1px, #ffffff 1px);
  background-size: 20px 20px;
  border-radius: 12px;
  border: 1px solid rgba(36, 20, 71, 0.06);
  box-shadow: 0 4px 24px rgba(36, 20, 71, 0.06);
  min-height: calc(100vh - 72px - 24px);
  overflow: visible;
}

.ld-page {
  display: flex;
  width: 100%;
  margin: 0;
  padding: 3.25rem 0 0;
  gap: 3rem;
}

.ld-sidebar {
  width: 220px;
  flex-shrink: 0;
  align-self: flex-start;
  position: sticky;
  top: 72px;
  z-index: 1015;
  max-height: calc(100vh - 88px);
  overflow-y: auto;
  overflow-x: hidden;
  padding-bottom: 0.5rem;
  background-color: #ffffff;
  background-image: radial-gradient(#ebe6f3 1px, #ffffff 1px);
  background-size: 20px 20px;
}

.ld-sidebar-label {
  font-family: 'Inter', sans-serif;
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 0.06em;
  color: #64748b;
  text-transform: uppercase;
  margin-bottom: 0.75rem;
}

.ld-sidebar nav {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.ld-sidebar nav a {
  font-family: 'Inter', sans-serif;
  font-size: 15px;
  font-weight: 400;
  color: #64748b;
  padding: 6px 10px;
  border-radius: 6px;
  border-left: 2px solid transparent;
  transition: all 0.2s;
  line-height: 1.4;
  text-decoration: none;
}

.ld-sidebar nav a:hover,
.ld-sidebar nav a.is-active {
  color: #0f696e;
  background: rgba(15, 105, 110, 0.08);
  border-left-color: #0f696e;
  text-decoration: none;
}

.ld-content {
  flex: 1;
  min-width: 0;
  position: relative;
  z-index: 0;
}

.ld-doc-header {
  position: sticky;
  top: 72px;
  z-index: 1020;
  margin-bottom: 2.5rem;
  padding-top: 0.5rem;
  padding-bottom: 2rem;
  border-bottom: 1px solid rgba(15, 105, 110, 0.15);
  background-color: #ffffff;
  background-image: radial-gradient(#ebe6f3 1px, #ffffff 1px);
  background-size: 20px 20px;
  box-shadow: 0 8px 16px -8px rgba(36, 20, 71, 0.08);
}

.ld-content > .ld-callout,
.ld-content > section,
.ld-content > .legal-doc-inner-footer {
  position: relative;
  z-index: 1;
}

.ld-doc-tag {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-family: 'Inter', sans-serif;
  font-size: 13px;
  font-weight: 500;
  letter-spacing: 0.06em;
  color: #0f696e;
  background: rgba(15, 105, 110, 0.1);
  border: 1px solid rgba(15, 105, 110, 0.2);
  padding: 4px 10px;
  border-radius: 20px;
  margin-bottom: 1rem;
  text-transform: uppercase;
}

.ld-doc-tag::before {
  content: '●';
  font-size: 7px;
}

.ld-doc-title {
  font-family: 'Inter', sans-serif;
  font-size: clamp(2rem, 4vw, 3.4rem);
  font-weight: 800;
  color: #241447;
  line-height: 1.15;
  margin-bottom: 0.75rem;
}

.ld-doc-meta {
  font-family: 'Inter', sans-serif;
  font-size: 15px;
  font-weight: 400;
  color: #49454f;
  line-height: 1.6;
}

.ld-doc-meta strong {
  color: #241447;
  font-weight: 600;
}

section {
  margin-bottom: 3rem;
}

.ld-section-number {
  font-family: 'Inter', sans-serif;
  font-size: 13px;
  font-weight: 600;
  color: #0f696e;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  margin-bottom: 0.5rem;
}

.ld-content h2 {
  font-family: 'Inter', sans-serif;
  font-size: clamp(1.5rem, 3.5vw, 2.25rem);
  font-weight: 800;
  line-height: 1.25;
  color: #241447;
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px solid rgba(15, 105, 110, 0.15);
}

.ld-content h3 {
  font-family: 'Inter', sans-serif;
  font-size: 18px;
  font-weight: 700;
  color: #241447;
  margin: 1.25rem 0 0.5rem;
  letter-spacing: normal;
}

.ld-content p {
  font-family: 'Inter', sans-serif;
  color: #49454f;
  margin-bottom: 0.75rem;
  font-weight: 400;
  line-height: 1.65;
  font-size: 15px;
}

.ld-content ul {
  padding-left: 1.25rem;
  margin-bottom: 0.75rem;
}

.ld-content li {
  font-family: 'Inter', sans-serif;
  font-size: 15px;
  color: #49454f;
  margin-bottom: 0.4rem;
  font-weight: 400;
  line-height: 1.65;
}

.ld-content li::marker {
  color: #0f696e;
}

.ld-content a {
  color: #0f696e;
  text-decoration: none;
  font-weight: 500;
}

.ld-content a:hover {
  text-decoration: underline;
}

.ld-callout {
  background: #f6f4fa;
  border: 1px solid rgba(36, 20, 71, 0.08);
  border-left: 3px solid #0f696e;
  border-radius: 8px;
  padding: 1rem 1.25rem;
  margin: 1.5rem 0;
  font-family: 'Inter', sans-serif;
  font-size: 15px;
  font-weight: 400;
  line-height: 1.65;
}

.ld-callout p {
  margin: 0;
  color: #49454f;
  line-height: 1.65;
}

.ld-callout p + p {
  margin-top: 0.75rem;
}

.ld-callout--warn {
  background: rgba(245, 158, 11, 0.1);
  border: 1px solid rgba(217, 119, 6, 0.22);
  border-left: 3px solid #d97706;
}

.ld-callout--warn p {
  color: #49454f;
}

.ld-callout--warn p strong {
  color: #b45309;
}

@media (min-width: 769px) {
  .legal-page-root {
    height: 100vh;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }

  .legal-page-frame {
    flex: 1 1 auto;
    min-height: 0;
    max-height: none;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }

  .ld-page {
    flex: 1 1 auto;
    min-height: 0;
    overflow: hidden;
  }

  .ld-sidebar {
    position: static;
    align-self: stretch;
    max-height: none;
    overflow-y: auto;
  }

  .ld-content {
    flex: 1 1 auto;
    min-height: 0;
    overflow-y: auto;
    overflow-x: hidden;
    -webkit-overflow-scrolling: touch;
  }

  .ld-doc-header {
    top: 0;
  }
}

@media (max-width: 768px) {
  .legal-page-root {
    height: auto;
    overflow: visible;
    display: block;
  }

  .legal-page-frame {
    flex: none;
    overflow: visible;
    display: block;
  }

  .ld-page {
    flex-direction: column;
    flex: none;
    overflow: visible;
    min-height: 0;
    padding: 1.75rem 0 2.5rem;
  }

  .ld-content {
    overflow: visible;
  }

  .ld-sidebar {
    width: 100%;
    position: static;
    max-height: none;
  }
}
</style>
