export const BILLING_RETURN_TO_KEY: string;
export const UPLOAD_RETURN_PATH: string;
export const FREEMIUM_RETEST_MESSAGE: string;
export const FREEMIUM_VISIBLE_ASSET_LIMIT: number;
export const FREEMIUM_TEAM_MEMBER_LIMIT: number;

export function isActiveSubscription(subscription: any): boolean;
export function isFreemiumPlan(planOrSubscription: any): boolean;
export function freemiumLocksUploadScope(subscription: any): boolean;
export function isInvalidScanFileMessage(text: any): boolean;
export function isNetworkOrTransportError(text: any): boolean;
export function isPlanQuotaMessage(text: any): boolean;
export function isExistingSubscriptionMessage(text: any): boolean;
export function isRetestBlockedMessage(text: any): boolean;
export function retestErrorMessage(apiMessage?: any, extras?: any): string;
export function planAssetLimit(planOrSubscription: any): number;
export function planBlocksOversizedUpload(planOrSubscription: any): boolean;
export function isFreemiumTeamLimitMessage(text: any): boolean;
export function parseFreemiumUpgrade(data: any): any;
export function freemiumUpgradeAssetCount(banner: any): number;
export function wasFreemiumCompletePopupShown(): boolean;
export function markFreemiumCompletePopupShown(): void;
export function collectFreemiumTrimmedResults(data: any): any[];
export function formatFreemiumTrimmedMessage(row?: any): string;
export function billingAssetBreakdown(source: any): any;
export function billableAssetCount(source: any, fallback?: number): number;
export function fullReportAssetCount(source: any, fallback?: number): number;
export function formatLockedUpgradeNotice(source: any): string;
export function storeBillableAssetCount(count: any): void;
export function peekBillableAssetCount(): number;
export function rememberFullAssetCount(source: any, fallback?: number): number;
export function suggestedPlanFromAssetCount(count: any): string;
export function planDisplayName(planOrSubscription: any): string;
export function otherPlans(suggested: any): string[];
export function setBillingReturnTo(path: any): void;
export function consumeBillingReturnTo(fallback?: string): string;
export function peekBillingReturnTo(): string;
export function clearBillingReturnTo(): void;
export function markFreemiumActiveNotice(): void;
export function consumeFreemiumActiveNotice(): boolean;
export function extraIpCount(total: any, limit: any): number;
export function parsePlanHintFromMessage(text: any): { count: number; suggested: string };
export function plansThatCoverCount(count: any): string[];
export function localPremiumEstimate(assetCount: any, mode?: any, billingCycle?: any): any;
